// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/service.go -destination=internal/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "test-backend-1-kuprinvv/internal/model"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// DummyLogin mocks base method.
func (m *MockAuthService) DummyLogin(ctx context.Context, userUUID uuid.UUID, role string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DummyLogin", ctx, userUUID, role)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DummyLogin indicates an expected call of DummyLogin.
func (mr *MockAuthServiceMockRecorder) DummyLogin(ctx, userUUID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DummyLogin", reflect.TypeOf((*MockAuthService)(nil).DummyLogin), ctx, userUUID, role)
}

// Login mocks base method.
func (m *MockAuthService) Login(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, email, password)
}

// Register mocks base method.
func (m *MockAuthService) Register(ctx context.Context, email, password, role string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, email, password, role)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceMockRecorder) Register(ctx, email, password, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthService)(nil).Register), ctx, email, password, role)
}

// MockSlotService is a mock of SlotService interface.
type MockSlotService struct {
	ctrl     *gomock.Controller
	recorder *MockSlotServiceMockRecorder
	isgomock struct{}
}

// MockSlotServiceMockRecorder is the mock recorder for MockSlotService.
type MockSlotServiceMockRecorder struct {
	mock *MockSlotService
}

// NewMockSlotService creates a new mock instance.
func NewMockSlotService(ctrl *gomock.Controller) *MockSlotService {
	mock := &MockSlotService{ctrl: ctrl}
	mock.recorder = &MockSlotServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlotService) EXPECT() *MockSlotServiceMockRecorder {
	return m.recorder
}

// GetSlots mocks base method.
func (m *MockSlotService) GetSlots(ctx context.Context, roomID uuid.UUID, date time.Time) ([]model.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlots", ctx, roomID, date)
	ret0, _ := ret[0].([]model.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlots indicates an expected call of GetSlots.
func (mr *MockSlotServiceMockRecorder) GetSlots(ctx, roomID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlots", reflect.TypeOf((*MockSlotService)(nil).GetSlots), ctx, roomID, date)
}

// MockBookingService is a mock of BookingService interface.
type MockBookingService struct {
	ctrl     *gomock.Controller
	recorder *MockBookingServiceMockRecorder
	isgomock struct{}
}

// MockBookingServiceMockRecorder is the mock recorder for MockBookingService.
type MockBookingServiceMockRecorder struct {
	mock *MockBookingService
}

// NewMockBookingService creates a new mock instance.
func NewMockBookingService(ctrl *gomock.Controller) *MockBookingService {
	mock := &MockBookingService{ctrl: ctrl}
	mock.recorder = &MockBookingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingService) EXPECT() *MockBookingServiceMockRecorder {
	return m.recorder
}

// CancelBooking mocks base method.
func (m *MockBookingService) CancelBooking(ctx context.Context, userID, bookingID uuid.UUID) (*model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBooking", ctx, userID, bookingID)
	ret0, _ := ret[0].(*model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelBooking indicates an expected call of CancelBooking.
func (mr *MockBookingServiceMockRecorder) CancelBooking(ctx, userID, bookingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBooking", reflect.TypeOf((*MockBookingService)(nil).CancelBooking), ctx, userID, bookingID)
}

// CreateBooking mocks base method.
func (m *MockBookingService) CreateBooking(ctx context.Context, userID, slotID uuid.UUID, createConferenceLink bool) (*model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, userID, slotID, createConferenceLink)
	ret0, _ := ret[0].(*model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockBookingServiceMockRecorder) CreateBooking(ctx, userID, slotID, createConferenceLink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockBookingService)(nil).CreateBooking), ctx, userID, slotID, createConferenceLink)
}

// GetMyBookings mocks base method.
func (m *MockBookingService) GetMyBookings(ctx context.Context, userID uuid.UUID) ([]model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyBookings", ctx, userID)
	ret0, _ := ret[0].([]model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyBookings indicates an expected call of GetMyBookings.
func (mr *MockBookingServiceMockRecorder) GetMyBookings(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyBookings", reflect.TypeOf((*MockBookingService)(nil).GetMyBookings), ctx, userID)
}

// ListBookings mocks base method.
func (m *MockBookingService) ListBookings(ctx context.Context, page, pageSize int) ([]model.Booking, *model.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookings", ctx, page, pageSize)
	ret0, _ := ret[0].([]model.Booking)
	ret1, _ := ret[1].(*model.Pagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBookings indicates an expected call of ListBookings.
func (mr *MockBookingServiceMockRecorder) ListBookings(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookings", reflect.TypeOf((*MockBookingService)(nil).ListBookings), ctx, page, pageSize)
}

// MockRoomService is a mock of RoomService interface.
type MockRoomService struct {
	ctrl     *gomock.Controller
	recorder *MockRoomServiceMockRecorder
	isgomock struct{}
}

// MockRoomServiceMockRecorder is the mock recorder for MockRoomService.
type MockRoomServiceMockRecorder struct {
	mock *MockRoomService
}

// NewMockRoomService creates a new mock instance.
func NewMockRoomService(ctrl *gomock.Controller) *MockRoomService {
	mock := &MockRoomService{ctrl: ctrl}
	mock.recorder = &MockRoomServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomService) EXPECT() *MockRoomServiceMockRecorder {
	return m.recorder
}

// CreateRoom mocks base method.
func (m *MockRoomService) CreateRoom(ctx context.Context, room model.Room) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, room)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRoomServiceMockRecorder) CreateRoom(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRoomService)(nil).CreateRoom), ctx, room)
}

// ListRooms mocks base method.
func (m *MockRoomService) ListRooms(ctx context.Context) ([]model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", ctx)
	ret0, _ := ret[0].([]model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockRoomServiceMockRecorder) ListRooms(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockRoomService)(nil).ListRooms), ctx)
}

// MockScheduleService is a mock of ScheduleService interface.
type MockScheduleService struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleServiceMockRecorder
	isgomock struct{}
}

// MockScheduleServiceMockRecorder is the mock recorder for MockScheduleService.
type MockScheduleServiceMockRecorder struct {
	mock *MockScheduleService
}

// NewMockScheduleService creates a new mock instance.
func NewMockScheduleService(ctrl *gomock.Controller) *MockScheduleService {
	mock := &MockScheduleService{ctrl: ctrl}
	mock.recorder = &MockScheduleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleService) EXPECT() *MockScheduleServiceMockRecorder {
	return m.recorder
}

// CreateSchedule mocks base method.
func (m *MockScheduleService) CreateSchedule(ctx context.Context, schedule model.Schedule) (*model.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, schedule)
	ret0, _ := ret[0].(*model.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockScheduleServiceMockRecorder) CreateSchedule(ctx, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockScheduleService)(nil).CreateSchedule), ctx, schedule)
}
