// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/client/client.go -destination=internal/mocks/mock_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConferenceClient is a mock of ConferenceClient interface.
type MockConferenceClient struct {
	ctrl     *gomock.Controller
	recorder *MockConferenceClientMockRecorder
	isgomock struct{}
}

// MockConferenceClientMockRecorder is the mock recorder for MockConferenceClient.
type MockConferenceClientMockRecorder struct {
	mock *MockConferenceClient
}

// NewMockConferenceClient creates a new mock instance.
func NewMockConferenceClient(ctrl *gomock.Controller) *MockConferenceClient {
	mock := &MockConferenceClient{ctrl: ctrl}
	mock.recorder = &MockConferenceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConferenceClient) EXPECT() *MockConferenceClientMockRecorder {
	return m.recorder
}

// CreateLink mocks base method.
func (m *MockConferenceClient) CreateLink(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockConferenceClientMockRecorder) CreateLink(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockConferenceClient)(nil).CreateLink), ctx)
}
